package post_restAssured;

public class Config {
	
	
    public static String token = "eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJBdWN0aW9uZWVyIl0sImFjdGl2ZSI6dHJ1ZSwibGFzdE5hbWUiOiJTaGFybWEiLCJ1c2VySWQiOiJkNmZjNGJjMS0zYjNiLTQ1MzEtODRiNy1kZDlhYzkyNDkyMmUiLCJmaXJzdE5hbWUiOiJESEFWQUwiLCJzdWIiOiJkaGF2YWwuc2hhcm1hIiwiaWF0IjoxNzM1MDI2NjMyLCJleHAiOjE3MzUwNTY2MzJ9.-pNFhVKHAfqRatoVnl_39HHG_Od5LK-v8fi4bBt1RHM";

}

