package put_restAssured;

public class Config {
	
	
    public static String token = "eyJhbGciOiJIUzI1NiJ9.eyJsYXN0TmFtZSI6IkRvZSIsInVzZXJJZCI6IjM0NTAwNjAyLTcyNmQtNGViNC05MWI2LTZhZjIxZDllOGRhMiIsImZpcnN0TmFtZSI6IndhZ2giLCJyb2xlcyI6WyJCaWRkZXIiXSwiYWN0aXZlIjp0cnVlLCJzdWIiOiJwcmFzaGFudCIsImlhdCI6MTczNDE2ODE4OSwiZXhwIjoxNzM0MTk4MTg5fQ.mkKIKe5CNCzlpgUkbxCDFKIlWrNR5WMAYak59xosmP0";

}

