package put_restAssured;

public class Config {
	
	
    public static String token = "eyJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJ3YWdoIiwicm9sZXMiOlsiQmlkZGVyIl0sImFjdGl2ZSI6dHJ1ZSwibGFzdE5hbWUiOiJEb2UiLCJ1c2VySWQiOiIzNDUwMDYwMi03MjZkLTRlYjQtOTFiNi02YWYyMWQ5ZThkYTIiLCJzdWIiOiJwcmFzaGFudCIsImlhdCI6MTczNDA2MzM5NiwiZXhwIjoxNzM0MDkzMzk2fQ.buOUJ33LdNJbt0iLXlLeYi-ZYk1LK2tH3K_8cgSEr0E";

}

